spring.application.name=TaskManagementSystem
# Server Configuration
server.port=8080
server.servlet.context-path=/task-manager
# Database Connection (Spring Data JPA / HikariCP)
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/TMS
spring.datasource.username=postgres
spring.datasource.password=abdulbar
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Explicitly specify the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL dialect
external.api.base-url=https://jsonplaceholder.typicode.com
logging.level.com.zaxxer.hikari=DEBUG
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000
# Docker Compose
#spring.docker.compose.enabled=true
#spring.docker.compose.lifecycle-management = start-and-stop