spring.application.name=TaskManagementSystem
# Server Configuration
server.port=8080
server.servlet.context-path=/task-manager
# Database Connection (Spring Data JPA / HikariCP)
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5433/TMS
spring.datasource.username=postgres
spring.datasource.password=abdulbar
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# Explicitly specify the PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL dialect
external.api.base-url=https://jsonplaceholder.typicode.com
logging.level.com.zaxxer.hikari=DEBUG
# Generate with: openssl rand -base64 32
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000
# Docker Compose
#spring.docker.compose.enabled=true
#spring.docker.compose.lifecycle-management = start-and-stop